apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: selena-hotel-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "hotel-db"  # Здесь оставляем тот же хост, если у тебя используется hotel-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hotel-service-secret  # Используем новый секрет
                  key: username  # Ключ из секрета для имени пользователя
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hotel-service-secret  # Используем новый секрет
                  key: password  # Ключ из секрета для пароля
