name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    permissions:
      packages: write   # Это разрешение для записи в пакеты (GHCR)
      contents: read    # Это разрешение для чтения содержимого репозитория

    steps:
      - name: Checkout code
        run: |
          if [ ! -d "selena-prod/hotels-service/.git" ]; then
            echo "Cloning the repository..."
            git clone git clone https://github.com/vitalii-q/selena-hotels-service selena-prod/hotels-service
          else
            echo "Repository already exists. Pulling the latest changes..."
            cd selena-prod/hotels-service && git pull
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          cd selena-prod/hotels-service
          docker build -t ${{ secrets.IMAGE_NAME }} .

      - name: Run tests
        run: |
          docker run ${{ secrets.IMAGE_NAME }} echo "Container is running"

      - name: Build Docker image
        run: |
          cd selena-prod/hotels-service
          docker build -t ghcr.io/${{ github.repository_owner }}/hotels-service:latest .

      # GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          docker login ghcr.io -u vitalii-q -p ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/selena-hotels-service/hotels-service:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull latest changes from selena-devops
        run: |
          git clone git@github.com:vitalii-q/selena-devops.git
          cd selena-devops
          git pull origin main

      - name: Remove existing containers
        run: |
          cd selena-prod
          docker-compose down || true

      - name: Deploy application
        run: |
          cd selena-prod
          docker-compose pull hotels-service
          docker-compose up -d hotels-service
