name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t selena-hotel-service .

      - name: Run tests (example, если у тебя есть тесты)
        run: |
          docker run selena-hotel-service echo "Container is running"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install K3s
        run: |
          curl -sfL https://get.k3s.io | sh -

      - name: Print KUBE_CONFIG
        run: mkdir -p ~/.kube
             echo "$KUBE_CONFIG" | head -n 10  # Выводит первые 10 строк kubeconfig для проверки
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Test kubectl connection
        run: |
          kubectl get pods --all-namespaces
      
      - name: Verify kubectl is working
        run: |
          kubectl version --client
          kubectl get nodes

      - name: Deploy to K3s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml